var dividends = Handlebars.template({"1":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "                            <tr>\r\n                                <td>"
    + escapeExpression(((helper = (helper = helpers.dividend || (depth0 != null ? depth0.dividend : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"dividend","hash":{},"data":data}) : helper)))
    + "</td>\r\n                                <td>"
    + escapeExpression(((helpers.formatDate || (depth0 && depth0.formatDate) || helperMissing).call(depth0, (depth0 != null ? depth0.exDividendDate : depth0), {"name":"formatDate","hash":{},"data":data})))
    + "</td>\r\n                                <td>"
    + escapeExpression(((helpers.formatDate || (depth0 && depth0.formatDate) || helperMissing).call(depth0, (depth0 != null ? depth0.recordDate : depth0), {"name":"formatDate","hash":{},"data":data})))
    + "</td>\r\n                                <td>"
    + escapeExpression(((helpers.formatDate || (depth0 && depth0.formatDate) || helperMissing).call(depth0, (depth0 != null ? depth0.datePayable : depth0), {"name":"formatDate","hash":{},"data":data})))
    + "</td>\r\n                                <td>"
    + escapeExpression(((helper = (helper = helpers.percentFranked || (depth0 != null ? depth0.percentFranked : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"percentFranked","hash":{},"data":data}) : helper)))
    + "</td>\r\n                                <th>"
    + escapeExpression(((helper = (helper = helpers.dividendIncome || (depth0 != null ? depth0.dividendIncome : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"dividendIncome","hash":{},"data":data}) : helper)))
    + "</th>\r\n                            </tr>\r\n";
},"3":function(depth0,helpers,partials,data) {
  return "<script src=\"/highstock.js\"></script>\r\n<script src=\"/exporting.js\"></script>\r\n";
  },"5":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "    $(function () {\r\n        $.getJSON('/priceSeries?ticker="
    + escapeExpression(((helper = (helper = helpers.ticker || (depth0 != null ? depth0.ticker : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ticker","hash":{},"data":data}) : helper)))
    + "', function (priceHistoryData) {\r\n            console.log(priceHistoryData);\r\n            $.getJSON('/dividendsSeries?ticker="
    + escapeExpression(((helper = (helper = helpers.ticker || (depth0 != null ? depth0.ticker : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ticker","hash":{},"data":data}) : helper)))
    + "', function (dividendHistoryData) {\r\n                var dividendData = [];\r\n                for(var i = 0; i < dividendHistoryData.length; i++) {\r\n                    var date = new Date(dividendHistoryData[i][0]);\r\n                    dividendData.push({\r\n                        title : 'D',\r\n                        x : Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()),\r\n                        text : '$' + dividendHistoryData[i][1]\r\n                    });\r\n                }\r\n                // Create the chart\r\n                $('#highchart_container').highcharts('StockChart', {\r\n                    rangeSelector: {\r\n                        selected: 5\r\n                    },\r\n                    scrollbar : {\r\n                        enabled : false\r\n                    },\r\n                    title: {\r\n                        text: '"
    + escapeExpression(((helper = (helper = helpers.ticker || (depth0 != null ? depth0.ticker : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ticker","hash":{},"data":data}) : helper)))
    + " Price Chart'\r\n                    },\r\n                    navigator : {\r\n                        enabled : false\r\n                    },\r\n                    series: [\r\n                        {\r\n                            id : 'pricechart',\r\n                            name: '"
    + escapeExpression(((helper = (helper = helpers.ticker || (depth0 != null ? depth0.ticker : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ticker","hash":{},"data":data}) : helper)))
    + "',\r\n                            data: priceHistoryData,\r\n                            tooltip: {\r\n                                valueDecimals: 2\r\n                            }\r\n                        },\r\n                        {\r\n                            type : 'flags',\r\n                            data : dividendData,\r\n                            onSeries : 'pricechart',\r\n                            shape : 'flag',\r\n                            width : 16\r\n                        }\r\n                    ]\r\n                });\r\n            });\r\n        });\r\n\r\n    });\r\n";
},"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = "﻿    <div class=\"row\">\r\n        <form class=\"pull-right\" style=\"width: 300px;\" role=\"form\">\r\n            <div class=\"col-xs-6\">\r\n                <div class=\"form-group\">\r\n                    <input name=\"ticker\" type=\"text\" placeholder=\"Stock symbol\" class=\"form-control\" value=\""
    + escapeExpression(((helper = (helper = helpers.ticker || (depth0 != null ? depth0.ticker : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"ticker","hash":{},"data":data}) : helper)))
    + "\">\r\n                </div>\r\n            </div>\r\n            <div class=\"col-xs-6\">\r\n                <button type=\"submit\" class=\"btn btn-success\">Get data!</button>\r\n            </div>\r\n        </form>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-md-3\">\r\n            <div class=\"panel panel-primary\">\r\n                <!-- Default panel contents -->\r\n                <div class=\"panel-heading\">Crucial statistics</div>\r\n                <!-- List group -->\r\n                <div class=\"list-group\">\r\n                    <a href=\"#\" class=\"list-group-item\">\r\n                        Forward yield <span class=\"badge\">\r\n                            "
    + escapeExpression(((helper = (helper = helpers.dividendYield || (depth0 != null ? depth0.dividendYield : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"dividendYield","hash":{},"data":data}) : helper)))
    + "%\r\n                        </span>\r\n                        <span class=\"glyphicon glyphicon-thumbs-up\" aria-hidden=\"true\"></span>\r\n                    </a>\r\n                    <a href=\"#\" class=\"list-group-item\">\r\n                        Trailing yield  <span class=\"badge\">"
    + escapeExpression(((helper = (helper = helpers.dividendYield || (depth0 != null ? depth0.dividendYield : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"dividendYield","hash":{},"data":data}) : helper)))
    + "%</span>\r\n                    </a>\r\n                    <a href=\"#\" class=\"list-group-item\">\r\n                        Retail deposit and investment rates; Banks' term deposits ($10000); 1 year  <span class=\"badge\">"
    + escapeExpression(((helper = (helper = helpers.termDeposit || (depth0 != null ? depth0.termDeposit : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"termDeposit","hash":{},"data":data}) : helper)))
    + "%</span>\r\n                    </a>\r\n                    <a href=\"#\" class=\"list-group-item\">\r\n                        Lending rates; Personal loans; Revolving credit; Home equity loans  <span class=\"badge\">"
    + escapeExpression(((helper = (helper = helpers.retailLandingRate || (depth0 != null ? depth0.retailLandingRate : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"retailLandingRate","hash":{},"data":data}) : helper)))
    + "%</span>\r\n                    </a>\r\n                    <a href=\"#\" class=\"list-group-item\">\r\n                        Last price <span class=\"badge\">"
    + escapeExpression(((helper = (helper = helpers.lastPrice || (depth0 != null ? depth0.lastPrice : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"lastPrice","hash":{},"data":data}) : helper)))
    + "</span>\r\n                    </a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"col-md-3\">\r\n            <div class=\"panel panel-primary\">\r\n                <!-- Default panel contents -->\r\n                <div class=\"panel-heading\">Recent dividend history</div>\r\n                <div class=\"table-responsive\">\r\n                    <table class=\"table\">\r\n                        <tr>\r\n                            <th>Dividend</th>\r\n                            <th>Ex Dividend Date</th>\r\n                            <th>Record Date</th>\r\n                            <th>Date Payable</th>\r\n                            <th>% Franked</th>\r\n                            <th>Dividend Income</th>\r\n                        </tr>\r\n                        <tbody>\r\n";
  stack1 = helpers.each.call(depth0, (depth0 != null ? depth0.dividends : depth0), {"name":"each","hash":{},"fn":this.program(1, data),"inverse":this.noop,"data":data});
  if (stack1 != null) { buffer += stack1; }
  buffer += "                        </tbody>\r\n                    </table>\r\n                    <div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"col-md-6\">\r\n            <div class=\"panel panel-primary\">\r\n                <div class=\"panel-heading\">Price history</div>\r\n                <div id=\"highchart_container\" style=\"position: absolute;width: 95%;\"></div>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n";
  stack1 = ((helpers.section || (depth0 && depth0.section) || helperMissing).call(depth0, "script", {"name":"section","hash":{},"fn":this.program(3, data),"inverse":this.noop,"data":data}));
  if (stack1 != null) { buffer += stack1; }
  stack1 = ((helpers.section || (depth0 && depth0.section) || helperMissing).call(depth0, "javascript", {"name":"section","hash":{},"fn":this.program(5, data),"inverse":this.noop,"data":data}));
  if (stack1 != null) { buffer += stack1; }
  return buffer + "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n";
},"useData":true});